import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { EvervaultProvider } from "@evervault/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <EvervaultProvider
      teamId={process.env.VITE_EV_TEAM_UUID as string}
      appId={process.env.VITE_EV_APP_UUID as string}
    >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </EvervaultProvider>
  );
}
