name: Build & Test
on:
  workflow_call:
    secrets:
      TESTS_TEAM_UUID:
        required: true
      TESTS_APP_UUID:
        required: true
      TESTS_DECRYPT_FN_KEY:
        required: true
      TURBO_TEAM:
        required: true
      TURBO_TOKEN:
        required: true

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      EV_TEAM_UUID: ${{ secrets.TESTS_TEAM_UUID }}
      EV_APP_UUID: ${{ secrets.TESTS_APP_UUID }}
      EV_DECRYPT_FN_KEY: ${{ secrets.TESTS_DECRYPT_FN_KEY }}
      VITE_EV_TEAM_UUID: ${{ secrets.TESTS_TEAM_UUID }}
      VITE_EV_APP_UUID: ${{ secrets.TESTS_APP_UUID }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 8.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps

      - name: Unit test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: E2E test
        run: pnpm run e2e:test
