name: Build and Deploy Staging

on:
  push:
    branches:
      - master

jobs:
  build-deploy-staging:
    environment:
      name: staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Inputs Staging
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
     
      - run: npm ci
      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PUBLIC_REPO_AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.PUBLIC_REPO_AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: 'us-east-1'

      - name: S3 Deploy
        run: aws s3 cp ./dist $AWS_S3_BUCKET --recursive && aws s3 cp ./public $AWS_S3_BUCKET --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}

      - name: Cloudfront Cache Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_STAGING }} --paths "/v1/index.js" "/v2/index.js"

  build-deploy-production:
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Inputs Staging
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
     
      - run: npm ci
      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PUBLIC_REPO_AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws-secret-access-key: ${{ secrets.PUBLIC_REPO_AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          aws-region: 'us-east-1'

      - name: S3 Deploy
        run: aws s3 cp ./dist $AWS_S3_BUCKET --recursive && aws s3 cp ./public $AWS_S3_BUCKET --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PRODUCTION }}

      - name: Cloudfront Cache Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_STAGING }} --paths "/v1/index.js" "/v2/index.js"
