name: Playwright Tests
on:
  push:
    branches: [main, master, v1]
  pull_request:
    branches: [main, master, v1]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          EV_TEAM_UUID: ${{ secrets.TESTS_TEAM_UUID }}
          EV_APP_UUID: ${{ secrets.TESTS_APP_UUID }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
