name: Pull Request Workflow
on:
  pull_request:
    branches:
      - "master"
      - "main"

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      TESTS_TEAM_UUID: ${{ secrets.TESTS_TEAM_UUID }}
      TESTS_APP_UUID: ${{ secrets.TESTS_APP_UUID }}
      TESTS_DECRYPT_FN_KEY: ${{ secrets.TESTS_DECRYPT_FN_KEY }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
