# Deploy package to production envrionment on release
# The tag names created by `changeset tag` include the name of the package we want to release

name: Main Release Workflow
on:
  push:
    tags:
      - "@evervault/*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      TESTS_TEAM_UUID: ${{ secrets.TESTS_TEAM_UUID }}
      TESTS_APP_UUID: ${{ secrets.TESTS_APP_UUID }}
      TESTS_DECRYPT_FN_KEY: ${{ secrets.TESTS_DECRYPT_FN_KEY }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  deploy-js:
    if: contains( github.ref, 'refs/tags/@evervault/browser')
    needs: build
    uses: ./.github/workflows/aws-generic-deploy-browser.yml
    with:
      environment: "production"
      name: "Deploy to Production"
      version: "v2"
    secrets:
      aws-access-key-id: ${{ secrets.PUBLIC_REPO_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.PUBLIC_REPO_AWS_SECRET_ACCESS_KEY }}
      aws-s3-bucket: ${{ secrets.BROWSER_SDK_S3_BUCKET }}
      aws-cloudfront-distribution-id: ${{ secrets.BROWSER_SDK_CLOUDFRONT_DISTRIBUTION_ID }}
  deploy-inputs:
    if: contains( github.ref, 'refs/tags/@evervault/inputs')
    needs: build
    uses: ./.github/workflows/aws-generic-deploy-inputs.yml
    with:
      environment: "production"
      name: "Deploy to Production"
      version: "v2"
    secrets:
      aws-access-key-id: ${{ secrets.PUBLIC_REPO_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.PUBLIC_REPO_AWS_SECRET_ACCESS_KEY }}
      aws-s3-bucket: ${{ secrets.INPUTS_S3_BUCKET }}
      aws-cloudfront-distribution-id: ${{ secrets.INPUTS_CLOUDFRONT_DISTRIBUTION_ID }}
  release:
    needs: build
    name: Release
    uses: softprops/action-gh-release@v1
    
