name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      name:
        description: 'Name of the job'
        required: true
        type: string
    secrets:
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
      aws-s3-bucket:
        description: 'AWS S3 Bucket'
        required: true
      aws-cloudfront-distribution-id:
        description: 'AWS Cloudfront Distribution ID'
        required: true

jobs:
  deploy-base:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: ${{ inputs.name }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: 'us-east-1'

      - name: Test inputs
        run: echo ${{ inputs.environment }}

      - name: Fake S3 Deploy
        run: echo $AWS_S3_BUCKET
        env:
          AWS_S3_BUCKET: ${{ secrets.aws-s3-bucket }}

      - name: Fake Cloudfront Cache Invalidation
        run: echo $AWS_CLOUDFRONT_DISTRIBUTION_ID
        env:
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.aws-cloudfront-distribution-id }}
