name: Test

on:
  push:
    branches: [main, master, v1]
  pull_request:
    branches: [main, master, v1]
jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test
        env:
          EV_TEAM_UUID: ${{ secrets.TESTS_TEAM_UUID }}
          EV_APP_UUID: ${{ secrets.TESTS_APP_UUID }}
